### ISSUE TITLE
CheatSheet suggestion for styling

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/react-native#595]
It took me a while to figure this out and I thought it might be worth sharing it in the docs somewhere. Maybe next to the other flatten example. What do you think?

```reason
open ReactNative;
open Theme;
// import default stylesheet from your js library

[@bs.module ("some-library", "SomeTheme")]
external defaultStyles: Js.t('a) = "SomeTheme";

// create new button color

let buttonBackgroundColor =
  Style.(style(~backgroundColor=Colors.primaryLight, ()));

// use flatten to change out the old color with the new color

let newButton =
  StyleSheet.flatten([|defaultStyles##button, buttonBackgroundColor|]);

/* logging the button before and after show the change being made
defaultStyles##button-before Object {
  "alignItems": "center",
  "backgroundColor": "#ff9900",
  "padding": 16,
}
defaultStyless##button-after Object {
  "alignItems": "center",
  "backgroundColor": "rgba(27, 37, 77, 1)",
  "padding": 16,
}
Js.log2("defaultStyles##button-before", defaultStyles##button);
defaultStyles##button #= newButton;
Js.log2("defaultStyles##button-after", defaultStyles##button);
*/

// overwrite the original style with your new style

defaultStyles##button #= newButton;
let buttonDisabledColor =
  Style.(style(~backgroundColor=Colors.primaryOpaque("0.6"), ()));
let newButtonDisabled =
  StyleSheet.flatten([|defaultStyles##buttonDisabled, buttonDisabledColor|]);

defaultStyles##buttonDisabled #= newButtonDisabled;
let sectionFooterColor = Style.(style(~color=Colors.primaryLight, ()));
let newSectionFooterLink =
  StyleSheet.flatten([|
    defaultStyles##sectionFooterLink,
    sectionFooterColor,
  |]);
defaultStyles##sectionFooterLink #= newSectionFooterLink;

// convience identifier to to pass to my function which takes a style object.
let theme = defaultStyles;
```

**Comment by MoOx** [comment]
For multiple reason, I would not recommend this method for multiple reason:

- StyleSheet.flatten should be avoided (perf & the fact that you could instead pass 2 values in the style props, the last one would win) 
- I would recommend for theming to use a runtime thing (context/hook). Otherwise if you change a theme, you have to "restart" your runtime? Eg I have in mind: auto dark mode (iOS 13 allows to change dark mode based on light/day hour). If you don't have a hook that listen to changes etc, you will have to reload your app, probably "just" to change a color scheme...

IMO it's better for dynamic update & maintenance to have "simpler" merge of style using Style.array/Style.arrayOption directly in components.

**Comment by idkjs** [comment]
Thank you for this feedback, @MoOx. I will look at it again.

**Comment by idkjs** [comment]
In this case I am modifying the stylesheet and passing as a prop to binding which has an optional theme prop. So wouldn't have any Style props to pass the values to anyway. Do you comment still work in this context?

the binding
```
[@bs.module "aws-amplify-react-native"]
// takes a react component and returns a react component with the same signature
external withAuthenticator:
  (React.component('props),~theme:Js.t('a)=?,unit) => React.component('props) =
  "withAuthenticator";
```
the call site.

```
module AppComponent = {
  open WithAuthenticator;
  let makeProps = TabNavWithProps.makeProps;
  let make =
    withAuthenticator(TabNavWithProps.make, ~theme=AmplifyTheme.theme, ());
};
```

Takes it from this: 
![original-theme](https://user-images.githubusercontent.com/2370391/64027317-72f2b480-cb0e-11e9-9520-f22d54bab95c.png)

To this:
![modified-theme](https://user-images.githubusercontent.com/2370391/64027338-7dad4980-cb0e-11e9-82cf-3d22407ceaa6.png)
